---
- name: Install ruby package
  become: true
  yum:
    name: "{{ item }}" 
    state: latest
  with_items:
    - git
    - openssl-devel
    - sqlite-devel
    - gcc
    - gcc-c++
    - readline-devel
    - mysql
    - mysql-devel
    - libselinux-python

- name: Install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv

- name: Add rbenv to PATH
  lineinfile: 
    path="~/.bash_profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"

- name: Eval rbenv init in ~/.bash_profile
  lineinfile: 
    path="~/.bash_profile"
    line='eval "$(rbenv init -)"'

- name: Load rbenv setting
  shell: bash -lc "source ~/.bash_profile"

- name: Install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

- name: Check ruby installed
  shell: bash -lc "rbenv versions | grep 3.1.2"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: true

- name: Install Ruby
  shell: rbenv install 3.1.2
  when: rbenv_check_install.rc == 1

- name: Set default Ruby version
  shell: bash -lc "rbenv global 3.1.2 && rbenv rehash"

- name: Install bundler and so on
  shell: bash -lc "gem install {{ item }}"
  with_items:
    - rbenv-rehash
    - bundler
    - rails -v "7.0.4"