# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.5
  ansible-playbook: orbss/ansible-playbook@0.0.5
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run: 
          name: deploy CloudFormation & set environment variables
          command: |
            aws cloudformation deploy --template-file cloudformation/raisetech13-vpc.yml --stack-name raisetech13-vpc
            aws cloudformation deploy --template-file cloudformation/raisetech13-ec2.yml --stack-name raisetech13-ec2
            aws cloudformation deploy --template-file cloudformation/raisetech13-rds.yml --stack-name raisetech13-rds
#  execute-variables:
#    executor: aws-cli/default
#    steps:
#      - checkout
#      - aws-cli/setup:
#          aws-access-key-id: AWS_ACCESS_KEY_ID
#          aws-region: AWS_DEFAULT_REGION
#          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
#      - run:
#          name: Install AWS CLI
#          command: |
#            INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=raisetech13" --query "Reservations[0].Instances[0].InstanceId" --output text)
#            IP_ADDRESS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
#            echo "export EC2_IP_ADDRESS=$IP_ADDRESS" >> $BASH_ENV

  execute-ansible: 
    executor: ansible-playbook/default
    parameters:
      inventory:
        default: NONEXISTENT_ANSIBLE_INVENTORY
        description: |
          Ansible inventory file. The default value must be empty,
          so do not store any value to this environment variable.
          The data must be registered in base64 format
        type: env_var_name
      playbook:
        description: |
          The path of Ansible playbook
        type: string
      private-key:
        default: NONEXISTENT_ANSIBLE_SSH_KEY
        description: |
          SSH private key file. The default value must be empty,
          so do not store any value to this environment variable.
          The data must be registered in base64 format
        type: env_var_name
    environment:
      VAULT-PASSWORD: echo VAULT-PASSWORD=$ANSIBLE_VAULT >> $BASH_ENV
    steps: 
      - checkout
      - run:
          name: set inventory file
          command: |
            sudo pip install awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_DEFAULT_REGION
            INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=raisetech13" --query "Reservations[0].Instances[0].InstanceId" --output text)
            IP_ADDRESS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
            sed -i "1a\ ansible_dev_target ansible_host=${IP_ADDRESS} ansible_connection=ssh ansible_user=ec2-user" ansible/inventory
      #echo "export EC2_IP_ADDRESS=$IP_ADDRESS" >> $BASH_ENV
      - add_ssh_keys:
          fingerprints:
            - "8a:34:6b:e6:47:18:d3:e6:02:24:43:3b:1c:4c:5f:96"
      - ansible-playbook/install:
          version: 2.10.7
      - run: 
          name: Get ansible-vault
          command: |
            echo $ANSIBLE_VAULT > vault-password.txt
      - ansible-playbook/playbook:
#          inventory: ansibe/inventory
          playbook: <<parameters.playbook>>
          private-key: <<parameters.private-key>>
          playbook-options: '-u ec2-user -i ansible/inventory --vault-password-file=vault-password.txt'

#  execute-serverspec:
#    docker:
#      - image: circleci/ruby:latest
#    steps:
#      - checkout
#      - add_ssh_keys: 
#          fingerprints:
#            - "8a:34:6b:e6:47:18:d3:e6:02:24:43:3b:1c:4c:5f:96"
#      - run:
#          name: test rails_app
#          command: |
#            gem install bundler
#            gem install serverspec 
#            gem install rake
#            gem install ed25519 -v '1.2'
#            gem install bcrypt_pbkdf -v '1.0'
#            cd serverspec
#            rake spec

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  RaiseTech-CircleCI:
    jobs:
      - execute-cloudformation
#      - execute-variables:
#          requires:
#            - execute-cloudformation
      - execute-ansible:
          requires:
            - execute-cloudformation
#           - execute-variables
#          inventory: ANSIBLE_INVENTORY
          playbook: ansible/playbook.yml
          private-key: ANSIBLE_SSH_KEY
 #     - execute-serverspec:
 #         requires:
 #           - execute-cloudformation
 #           - execute-ansible