---
- name: remove the MariaDB
  become: true
  yum:
    name: mariadb-*
    state: absent

- name: install the mysql repo to yum
  become: true
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-5.noarch.rpm
    state: present

- name: install the mysql-community-server
  become: true
  yum: 
    name: --enablerepo=mysql80-community mysql-community-server
    state: present

- name: install the mysql-community-devel
  become: true
  yum:
    name: --enablerepo=mysql80-community mysql-community-devel

- name: make mysql logfile
  become: true
  template: 
    src: roles/mysql/templates/mysqld.log.j2
    dest: /var/log/mysqld.log
    owner: ec2-user
    group: ec2-user
    mode: '0774'

- name: start mysql by default
  become: true
  service:
    name: mysql
    state: started
