AWSTemplateFormatVersion: 2010-09-09
Resources:
#EC2の作成
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: raisetech04 
      ImageId: ami-0e25eba2025eea319
      InstanceType: t2.micro
      Monitoring: false
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue publicsubnet1c
          GroupSet:
           - !ImportValue secGroupName1
      UserData:
        Fn::Base64: !Sub |
         #!/bin/bash
         sudo yum -y update
         sudo yum remove -y mariadb-*
         sudo yum install -y mysql
         sudo service mysqld start
      Tags:
        - Key: Name
          Value: raisetech10
Outputs:
# EC2
  l10EC2:
    Value: !Ref myEC2Instance
    Export:
      Name: l10-ec2