---
  - name:  Nginx exists
    stat: 
      path: /etc/nginx
    register: nginx_repo

  - name: Install Nginx
    become: true
    command:  sudo yum install -y nginx
    when: not nginx_repo.stat.exists 
    changed_when: false


#  - name: Settings Nginx
#    become: true
#    copy:
#      src: roles/nginx/templates/nginx.conf
#      dest: /etc/nginx/nginx.conf

  - name: Start Nginx
    become: true
    service:
      name: nginx
      enabled: true
