#!/usr/bin/env python
import os
import json
import boto3

# AWSリージョンを設定
aws_region = os.environ.get('AWS_DEFAULT_REGION')

# CircleCIの環境変数からAWSのアクセスキーとシークレットキーを取得
aws_access_key = os.environ.get('AWS_ACCESS_KEY_ID')
aws_secret_key = os.environ.get('AWS_SECRET_ACCESS_KEY')

# Boto3セッションを作成
session = boto3.Session(
    aws_access_key_id=aws_access_key,
    aws_secret_access_key=aws_secret_key,
    region_name=aws_region
)

# EC2クライアントを作成
ec2 = session.client('ec2')

# インスタンスの情報を取得
response = ec2.describe_instances()

# Ansibleのインベントリ情報を格納するためのディクショナリを作成
ansible_inventory = {
    '_meta': {
        'hostvars': {}
    }
}

# インスタンス情報をループしてインベントリに追加
for reservation in response['Reservations']:
    for instance in reservation['Instances']:
        # インスタンスのパブリックIPアドレスを取得
        public_ip = instance.get('PublicIpAddress', None)
        
        if public_ip:
            # インスタンスのタグから名前を取得
            for tag in instance['Tags']:
                if tag['Key'] == 'Name':
                    hostname = tag['Value']
                    break
            else:
                # 名前がない場合、インスタンスIDを使用
                hostname = instance['InstanceId']

            # インベントリにホストを追加
            ansible_inventory[hostname] = {
                'ansible_host': public_ip,
                'ansible_user': 'your_ssh_user',
                # 他の必要な変数をここに追加できます
            }

# インベントリ情報をJSON形式で出力
print(json.dumps(ansible_inventory))